/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chargily.epay.java;

import org.junit.jupiter.api.Test;

import static java.lang.System.out;

class ChargilyTest {
    @Test void createInvoiceReturnsCheckoutUrl() {
        ChargilyClient client = new ChargilyClient("api_KFWtdBczv0qnAMHNxGXCGVK93yEZahZwr4EgFa4xmfnLTIJkezPvW0LgqholrC7S");
        Invoice invoice = new Invoice(
                "Chakhoum Ahmed",
                "rainxh11@gmail.com",
                5.0,
                "https://backend.com/webhook_endpoint",
                "https://frontend.com",
                PaymentMethod.EDAHABIA,
                "5001",
                10000.0
                 );
        try {
            var response = client.createInvoice(invoice);
            out.println(response.body().checkoutUrl);
        } catch (Exception e) {
            out.println(e.getMessage());
        }
    }
}
